# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Meerk40t

on:
  push:
    tags:
      - 'v[0-9]+.*'
  workflow_dispatch:

jobs:
  build-ubuntu:

    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout meerk40t
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install libgtk-3-dev
        python3 -m pip install --upgrade pip
        pip3 install pyinstaller wheel
        pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Build meerk40t
      run: |
        mv meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t mk40t.py
        mv mk40t.py meerk40t.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/meerk40t
          asset_name: MeerK40t
          asset_content_type: application/exe

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout meerk40t
      uses: actions/checkout@v2

    - name: Set outputs
      id: vars
      run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
    - name: Check outputs
      run: |
          echo ${{ steps.vars.outputs.sha_short }}
          echo ${{ steps.vars.outputs.tag }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: 'x86'
# Yikes. ch341dll.dll is not compatible with 64-bit python/pyinstaller/ctypes

    - name: Install dependencies
      run: |
        pip install wheel
        pip install wxPython==4.0.7-post2
        pip install meerk40t-camera ezdxf opencv-python-headless

#       Compile bootloaders in order to reduce virus totals
    - name: Build pyinstaller, generate bootloaders
      run: |
        git clone --depth=1 https://github.com/pyinstaller/pyinstaller
        cd pyinstaller/bootloader
        python3 ./waf distclean all --target-arch=32bit
        cd ..
        python3 setup.py install
        cd ..

#    - name: Directory structure
#      run: |
#        tree D:/ /a /f

    - name: Build MeerK40t
      run: |
        move meerk40t.py mk40t.py
        pyinstaller --windowed --onefile --name meerk40t .github/workflows/win/meerk40t.spec
        move mk40t.py meerk40t.py

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: release-${{ steps.vars.outputs.tag }}
          release_name: ${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/meerk40t.exe
          asset_name: MeerK40t.exe
          asset_content_type: application/exe
