# Add labels to Pull-Requests based on the types of files modified
name: "Pull Request Labeler"
on:
- pull_request
- pull_request_target

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"