name: Python code quality

on:
  push:
    branches: [main, legacy, 0.7]
  pull_request:
    branches: [main, legacy, 0.7]
  schedule:
    - cron: '0 22 * * 5'

concurrency:
  group: codequality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:

    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('requireoptions.txt') }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel babel
        pip install --upgrade --upgrade-strategy eager pylint flake8 flake8-deprecated black mypy isort
        wget -nv https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl
        pip install wxPython-4.1.1-cp38-cp38-linux_x86_64.whl
        if [ -f requireoptions.txt ]; then pip install --upgrade --upgrade-strategy eager -r requireoptions.txt; fi

    - name: Create output directory
      run: mkdir -p artifiacts

    - name: Analyse with pylint
      id: pylint
      continue-on-error: true
      run: |
        pylint --rcfile=.pylintrc --ignore=svgelements.py --output-format=text:artifiacts/pylint.txt,colorized meerk40t

    - name: Analyse with flake8
      id: flake8
      continue-on-error: true
      run: |
        flake8 meerk40t --tee --output-file=artifiacts/flake8.txt

    - name: Analyse with black
      id: black
      continue-on-error: true
      run: |
        black --diff --color meerk40t

    - name: Analyse with isort
      id: isort
      continue-on-error: true
      run: |
        isort meerk40t -c --diff

# MK Not strongly typed - mypy is not going to be run
#    - name: Analyse with mypy
#      id: mypy
#      continue-on-error: true
#      run: |
#        mypy meerk40t
#        exit 0

    - name: Upload analysis results
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: artifacts/

    - name: "Set status"
      run: |
        if ${{ steps.pylint.outcome != 'success' || steps.flake8.outcome != 'success' || steps.black.outcome != 'success' || steps.isort.outcome != 'success' }}; then
         exit 1
        fi
